# Generated by Django 4.2.6 on 2023-10-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
